# Server Configuration
server:
  port: 8080

# Spring Boot Configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hello?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
