import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    val kotlinVersion = "1.3.50"

    kotlin("jvm") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
    
    // Use JPA plugin for data class default constructor
    kotlin("plugin.jpa") version kotlinVersion

    id("jacoco")
    id("org.springframework.boot") version "2.2.1.RELEASE"
    id("io.spring.dependency-management") version "1.0.8.RELEASE"
    application
}

group = "com.kotlin.spring.hello"
version = "1.0-SNAPSHOT"

allprojects {
    dependencies {
        // Use the Kotlin JDK 8 standard library.
        implementation(kotlin("stdlib-jdk8"))

        testCompile("junit:junit:4.12")
    }

    val compileKotlin: KotlinCompile by tasks
    compileKotlin.kotlinOptions {
        jvmTarget = "1.8"
    }
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    val postgresqlVersion = "42.2.8"

    // Use Kotlin reflect for Spring boot annotation(e.g. @Service, @Component)
    implementation(kotlin("reflect"))

    // Use Spring boot
    implementation("org.springframework.boot:spring-boot-starter-web")

    // Use Spring data JPA
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    // Use PostgreSQL
    implementation("org.postgresql:postgresql:$postgresqlVersion")

    // Use kotlin test
    testImplementation(kotlin("test"))

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Use Spring boot test
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

application {
    // Define the main class for the application.
    mainClassName = "com.kotlin.spring.hello.AppKt"
}
